### ISSUE TITLE
The page could not be found or we don't have permission to view it.

### ISSUE THREAD

**Issue by shweta647** [ArtemKushnerov/az#1]
remote: The project you were looking for could not be found.
fatal: repository 'https://gitlab.com/comma-project/adownloader.git/' not found
while running-> pip install -e git+https://gitlab.com/comma-project/adownloader.git@v1.0.1#egg=az

**Comment by ArtemKushnerov** [comment]
Dear shweta,
There was a mistake in readme. Please, use github repository to download the tool, that is 
pip install -e git+git@github.com:ArtemKushnerov/az.git@v1.0.1#egg=az
or
pip install -e git+https://github.com/ArtemKushnerov/az.git@v1.0.1#egg=az
depending on the preferred way of authentication.

Let me know if the issue persists.
