### ISSUE TITLE
Key is not defined error

### ISSUE THREAD

**Issue by akshaymathur05** [ArtemKushnerov/az#13]
Hi @ArtemKushnerov , 
I am getting 
`Key is not defined. Please, define configuration parameter 'key' in local or global configInput file is not defined.`

I have defined it in the configInput.az file. The file is placed locally in my target directory.
`key=cb428d39eff8f9977f95a3c.....
input_file=C:\Users\Akshay Mathur\Desktop\Androzoo`
 Kindly help me out on how to resolve this issue

**Comment by hhhwwwuuu** [comment]
hey bro, how did you resolve it? I have same error now./.

**Comment by ArtemKushnerov** [comment]
The name of the file should be .az .

**Comment by SaimaAkbar** [comment]
same error can any one help 
Key is not defined. Please, define  configuration parameter 'key' in local or global config Input file is not defined.
