### ISSUE TITLE
Input file is not defined

### ISSUE THREAD

**Issue by gianlucascoccia** [ArtemKushnerov/az#16]
I'm trying to use the tool to download some apks.
I have done various attempts, last with this command taken from another issue:

`az -n 15 -d 2019-01-01: -s :3000000 -vt 5:50000 -k XXX` 

And as  a result I get: 

`Input file is not defined. `

Why would I need to specify an input file if I am downloading random apks? Moreover, what columns should I include in this input file? This information is not present in the docs. I made several attempts and I always get a 0 apks satisfy the criteria with any kind of input file.

**Comment by vijayantajain** [comment]
You don't need to create any input file, the input file can be downloaded from [here](https://androzoo.uni.lu/lists). This is stated right above the Configuration heading. I believe the input file is used to identify the files to download.

**Comment by ArtemKushnerov** [comment]
Hi @gianlucascoccia. What is meant by input file is the file you can download from here https://androzoo.uni.lu/lists . There's a huge csv. Then create .az configuration file in your home directory specifying path to the file you downloaded. Hope that helps.
