### ISSUE TITLE
Is it a bug?

### ISSUE THREAD

**Issue by Ken-HUST** [ArtemKushnerov/az#4]
![image](https://user-images.githubusercontent.com/28556735/41720526-ea7e5830-7595-11e8-8c22-7102818f469f.png)

I just want to download the benign apks, so I choose the option -vt 0:0. However, the number of satisfied apks is 5845415 which is the total number of AndroZoo's apks.

**Comment by ArtemKushnerov** [comment]
Hi, Ken. Thx for posting. it looks like a bug, I will look into it.

**Comment by ArtemKushnerov** [comment]
Hey, Ken, I've fixed the issue. Please,  install v1.2.1 and try again.
