### ISSUE TITLE
Warning: HTTP code for XXXXXX is 400

### ISSUE THREAD

**Issue by Ken-HUST** [ArtemKushnerov/az#5]
When I use the new version 1.2.1, I face another problem.
![http_code400](https://user-images.githubusercontent.com/28556735/42496026-688c1bc0-8457-11e8-9176-ae536db4ccd4.png)
And the size of all the apks that I downloaded is 31byte.
![http_code400_1](https://user-images.githubusercontent.com/28556735/42496300-218f7a36-8458-11e8-9a85-25bfcacd94cf.png)

**Comment by ArtemKushnerov** [comment]
Ken,  it isn't reproducing for me, I suspect that maybe androzoo was experiencing some issues. Is the issue still persisting?

**Comment by ArtemKushnerov** [comment]
Ken, did the issue get resolved?

**Comment by Ken-HUST** [comment]
Sorry. I tried different versions of az with different versions of python in the past few days. However, every time I encountered the same problem. I guess it may be a problem with the school network. I will wait a few more days to see if it is because of the school holiday now.
Thanks a lot!

**Comment by ArtemKushnerov** [comment]
Ken, try to download some apks via browser or curl as described here https://androzoo.uni.lu/api_doc. If the result is still the same, the problem indeed is in your network.

**Comment by Ken-HUST** [comment]
Thanks a lot! I have found the reason why I encountered the 'HTTP 400'. When I configured the .az file, I wrote a wrong APIkey(one letter is missing o(╥﹏╥)o). Now everything is okay, Thanks a lot!

**Comment by Ken-HUST** [comment]
On the other hand, can az provide the option relate to malware family selection?

**Comment by ArtemKushnerov** [comment]
Great. I will look at the malware families as soon as I have time.
