### ISSUE TITLE
Expand docs a bit

### ISSUE THREAD

**Issue by Sebastiaan-Alvarez-Rodriguez** [ArtemKushnerov/az#7]
Good day to you!
Today, I was playing with this nice tool. However, it did not understand my command.
My command was
```az -n 15 -d 2019-01-01: -s :3000000 -vt 5```
I believed this meant: Get me 15 apks, from 2019-01-01 or newer, with size 3 mb or less, and flagged as malicious by 5 or more analysis tools.

Documentation stated that ```-vt``` takes an integer argument.

By looking into the source code, I was able to figure out that a range X:Y is the actual argument, making the command look like ```az -n 15 -d 2019-01-01: -s :3000000 -vt 5:50000```.

Could you update your documentation (and expand the example to use ```-vt``` maybe?)

Have a nice day,
Sebastiaan

**Comment by ArtemKushnerov** [comment]
Hi, Sebastian. Good point, I will take care about that.

**Comment by Sebastiaan-Alvarez-Rodriguez** [comment]
Alright thanks!
